# =============================================================================
# Ansible Inventory — TravelMemory MERN Application
# =============================================================================
# Populated with Terraform output values
# =============================================================================

[webserver]
web ansible_host=3.110.87.209 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/travelmemory-key.pem

[dbserver]
db ansible_host=10.0.2.76 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/travelmemory-key.pem ansible_ssh_common_args='-o ProxyJump=ubuntu@3.110.87.209'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
